// import { Geist, Geist_Mono } from "next/font/google";
// import 'bootstrap/dist/css/bootstrap.css';
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Beyond Bikes",
//   description: "Generated by beyond bikes",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

// SEO

import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Beyond Bikes",
  description:
    "Beyond Bikes offers affordable and reliable electric bike rentals in Melbourne. Flexible 6–8h, 8–10h, and 10–12h hire options for commuters and delivery riders.",
  keywords:
    "Beyond Bikes rentals Melbourne, e-bike hire Melbourne, Melbourne bike rental, electric bikes for delivery, hourly e-bike hire, affordable e-bike rental",
  openGraph: {
    title: "Beyond Bikes | Melbourne E-Bike Rentals",
    description:
      "Rent premium electric bikes in Melbourne. Perfect for commuters and delivery professionals. Flexible hire durations and great rates.",
    url: "https://www.beyondbikes.com.au/",
    siteName: "Beyond Bikes",
    images: [
      {
        url: "/og-image.jpg", // Replace with your OG image path
        width: 1200,
        height: 630,
        alt: "Beyond Bikes Electric Bike Rentals",
      },
    ],
    locale: "en_AU",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Beyond Bikes | Melbourne E-Bike Rentals",
    description:
      "Affordable and reliable electric bike rentals in Melbourne. Flexible hire for commuters & delivery riders.",
    images: ["/og-image.jpg"], // Replace with your OG image path
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
